version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    hostname: wc-exchange
    container_name: wc-exchange-postgres
    restart: always
    user: "${UID_GID}"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5